name: Votifier
main: com.vexsoftware.votifier.NuVotifierBukkit
version: maven-version-number
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [Ichbinjoe, ParallelBlock, blakeman8192, Kramer, tuxed, Dragoboss]
api-version: 1.13

commands:
  nvreload:
    description: Reloads the NuVotifier configuration
    permission: nuvotifier.console
    permission-message: "You do not have permission to run this command."
    usage: "/nvreload"
